version: "3"
services:
    client:
        image: python:3.11
        container_name: kf-client
        volumes:
            - .:/app
        environment:
            - TZ=Asia/Shanghai
        network_mode: bridge
        working_dir: /app
        tty: true
        command: ["sh","docker-entrypoint.sh"]
