version: "3"
services:
    server:
        image: python:3.11
        volumes:
            - ./server:/server
        environment:
            - TZ=Asia/Shanghai
        network_mode: bridge
        working_dir: /server
        ports:
            - 8080:5000
            - 8081:5001
        tty: true
        command: ["sh","docker-entrypoint.sh"]
