services:
    client:
        image: python:3.11
        container_name: kf-client
        volumes:
            - .:/app
        environment:
            - TZ=Asia/Shanghai
            - GIT_REMOTE=https://github.com/yyned2501/frds_client.git
        network_mode: bridge
        working_dir: /app
        ports:
            - 8880:5001
        tty: true
        command: ["sh","docker-entrypoint.sh"]
